from flask import Flask, render_template, request
import pandas as pd
import joblib

model = joblib.load(open("mnb.jb", "rb"))
vector = joblib.load(open("vectorizer.jb", "rb"))


app = Flask(__name__)


@app.route('/')
def index():
    return render_template("index.html")

@app.route('/learn_more')
def learn_more():
    return render_template("learn_more.html")

@app.route('/get_started', methods=["GET", "POST"])
def get_started():
    return render_template("get_started.html")

@app.route('/predict', methods=["GET", "POST"])
def predict():
        if request.method == "POST":
             
           text = request.form.get("text")

           user = vector.transform([text])

           prediction = model.predict(user)[0]

           return render_template("get_started.html" , predict_text = f"The given text is generated by :-  {prediction}")



if __name__ == "__main__":
    app.run(debug = True)

